### ISSUE TITLE
Pretrained checkpoints

### ISSUE THREAD

**Issue by shivmgg** [falcon-xu/LGViT#1]
Thanks for the awesome work!

Can you please provide pre-trained checkpoints?

**Comment by falcon-xu** [comment]
> Thanks for the awesome work!
> 
> Can you please provide pre-trained checkpoints?


Hi, @shivmgg ,
Thank you very much for your interest in the project.
I'm deeply involved in writing a paper, which is critical and has a tight deadline. 
As soon as I have some time, I will address it immediately. 

Best,
Falcon

**Comment by shivmgg** [comment]
Hi @falcon-xu, please provide the checkpoints if you have time. 

Regards,
Shivam

**Comment by leo1200213** [comment]
Thanks for your insightful work! Can u provide checkpoints recently for reproducing your result?

Regards,
Leo

**Comment by ionymikler** [comment]
Hi @falcon-xu,
do you think you'll have the time to provide the pre-trained checkpoints any time in the next month?

My work takes inspiration from yours and would love to use it for benchmarking!

**Comment by falcon-xu** [comment]
Hi, @ionymikler @leo1200213 , we will upload checkpoints as soon as possibile.
You can follow the [collection](https://huggingface.co/collections/FALcon6/lgvit-6721e579f9d2e8c92ee430d6).

Regards,
Falcon
